- a
- akesi
- anu
- ala
- alasa
- ale
- ali
- ante
- anpa
- awen
- ijo
- ike
- ilo
- insa
- uta
- utala
- unpa
- e
- esun
- en
- o
- oko
- ona
- open
- olin
- kasi
- kama
- kala
- kalama
- kipisi
- kili
- kiwen
- kin
- kute
- kulupu
- kule
- kepeken
- ken
- ko
- kon
- sama
- sike
- sitelen
- sina
- sijelo
- sin
- sinpin
- suno
- supa
- suli
- suwi
- seme
- seli
- selo
- sewi
- sona
- soweli
- taso
- tawa
- tan
- tu
- telo
- tenpo
- toki
- tomo
- nasa
- nasin
- namako
- nanpa
- ni
- nimi
- nena
- noka
- pakala
- pana
- pali
- palisa
- pan
- pi
- pini
- pipi
- pimeja
- pilin
- poka
- poki
- pona
- ma
- mani
- mama
- mi
- mije
- mu
- musi
- mute
- mun
- meli
- moku
- moli
- monsi
- monsuta
- jaki
- jan
- jelo
- jo
- la
- laso
- lape
- lawa
- li
- lipu
- lili
- linja
- luka
- lukin
- lupa
- lete
- len
- loje
- lon
- waso
- walo
- wawa
- wan
- wile
- weka